# Generated by Django 5.1.1 on 2024-10-03 21:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppAccount', '0001_initial'),
        ('AppAgency', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccount',
            name='user_agency',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.PROTECT, to='AppAgency.agency'),
            preserve_default=False,
        ),
    ]
